 set nocompatible

 syntax on
 filetype on
 let myfiletypefile = "~/.vimfiletype"

 " change default highlighting to be more GNOME-friendly
 highlight Comment ctermfg=green

 set backspace=indent,eol,start	" more powerful backspacing

 " let our files override default options.
 set modeline 
 set modelines=5
 
 " BEGIN Coding Style Guidelines settings: 
 set expandtab
 set tabstop=4      " default 4 spaces tabs
 set shiftwidth=4
 set autoindent		" always set autoindenting on
 " END Coding Style Guidelines

 set ruler		" show the cursor position all the time
 set showcmd
 set showmatch
 set ignorecase " search ignores case
 set incsearch  " start searching as soon as first char is typed
 set autowrite  " automatically save file before certain commands, like :make

 " experimental options. remove if they mess stuff up
 set smarttab
 set textwidth=0

 set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%y]\ [ASCII=\%03.3b]\ [HEX=0x\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
 set laststatus=2

 autocmd FileType make set noexpandtab
 autocmd FileType make set textwidth=0
 autocmd FileType make set tabstop=8
 autocmd FileType make set shiftwidth=8
 autocmd FileType make set autoindent

 autocmd FileType mail set expandtab
 autocmd FileType mail set textwidth=72
 autocmd FileType mail set tabstop=4
 autocmd FileType mail set shiftwidth=4
 autocmd FileType mail set noautoindent

 "source ~/.vim-foldpython.vim
 "source ~/.vim/ccase.vim
